version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-billing-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l0ep9n0m8gsq"
s3_prefix = "sam-billing-stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MainEngineRole=\"arn:aws:iam::754084371841:role/main-engine-lambda-role\" FunctionTimeout=\"3\" UsersRole=\"arn:aws:iam::754084371841:role/main-engine-users-lambda-role\""
image_repositories = []
