AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  billing-app

  Sample SAM Template for billing-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.9
    MemorySize: 128
    Timeout: !Ref FunctionTimeout
    Handler: function.lambda_handler
    Layers:
        - !Ref Utils
        - 'arn:aws:lambda:eu-west-1:754084371841:layer:pymysql-layer:1'
    Environment:
        Variables:
          DB_ENDPOINT: billing-system-rds.cpgiferzxcuv.eu-west-1.rds.amazonaws.com
          DB_NAME: billappDB
          SECRET_ARN: arn:aws:secretsmanager:eu-west-1:754084371841:secret:billing-database-credentials-Z74qEc      
    VpcConfig:
        SecurityGroupIds:
          - sg-03ef30065e8e1c030
          - sg-0ee34adee005acbf6
        SubnetIds:
          - subnet-02afd2bac133457a9      
  
Parameters:
  MainEngineRole:
    Type: String
    Default: arn:aws:iam::754084371841:role/main-engine-lambda-role
  FunctionTimeout:
    Type: Number
    Default: 10
  UsersRole:
    Type: String
    Default: arn:aws:iam::754084371841:role/main-engine-users-lambda-role


Resources:
  BillingApi:
    Type: 'AWS::Serverless::Api'
    Properties:      
      Name: billing-api
      StageName: dev1
      OpenApiVersion: "3.0.1"
      DefinitionUri: ./oas.yaml          
      EndpointConfiguration:
        Type: REGIONAL
  
  Utils:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: utils/
      Description: Utilities layer for main engine functions
      LayerName: main-engine-utils
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
      

  # Services
  ListServices:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: services/list_services/
      Description: List Services    
      FunctionName: services-list-services      
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /services
            RestApiId: !Ref BillingApi
  
  AddService:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: services/add_service/
      Description: Add Service
      FunctionName: services-add-service
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: POST
            Path: /services
            RestApiId: !Ref BillingApi 
   
  UpdateService:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: services/update_service/
      Description: Update Service
      FunctionName: services-update-service
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: PATCH
            Path: /services/{id}
            RestApiId: !Ref BillingApi 

  DeleteService:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: services/delete_service/
      Description: Delete Service
      FunctionName: services-delete-service
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: DELETE
            Path: /services/{id}
            RestApiId: !Ref BillingApi 

  # Accounts
  ListAccounts:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/list_accounts/
      Description: List Accounts
      FunctionName: accounts-list-accounts
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /accounts
            RestApiId: !Ref BillingApi 

  ListAccountsAdmin:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/list_accounts_admin/
      Description: List Accounts
      FunctionName: accounts-list-accounts-admin
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /accounts/admin
            RestApiId: !Ref BillingApi 

  AddAccount:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/add_account/
      Description: Add Account
      FunctionName: accounts-add-account
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: POST
            Path: /accounts
            RestApiId: !Ref BillingApi 
  
  GetAccount:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/get_account/
      Description: Get Account
      FunctionName: accounts-get-account
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /accounts/{id}
            RestApiId: !Ref BillingApi 

  GetAccountAdmin:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/get_account_admin/
      Description: (Admin) Get Account
      FunctionName: accounts-get-account-admin
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /accounts/{id}/admin
            RestApiId: !Ref BillingApi 
  
  UpdateAccount:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/update_account/
      Description: Update Account
      FunctionName: accounts-update-account
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: PATCH
            Path: /accounts/{id}
            RestApiId: !Ref BillingApi 

  DeleteAccount:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/delete_account/
      Description: Delete Account
      FunctionName: accounts-delete-account
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: DELETE
            Path: /accounts/{id}
            RestApiId: !Ref BillingApi 
  
  # Organizations
  ListOrganizations:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: organizations/list_organizations/
      Description: List Organizations
      FunctionName: organizations-list-organizations
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /organizations
            RestApiId: !Ref BillingApi 
  
  FindOrganizations:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: organizations/find_organizations/
      Description: Find Organizations
      FunctionName: organizations-find-organizations
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /organizations/find
            RestApiId: !Ref BillingApi 
  
  AddOrganization:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: organizations/add_organization/
      Description: Add Organization
      FunctionName: organizations-add-organization
      Environment:
        Variables:
          USER_POOL_ID: eu-west-1_O0r17DvOM
      Role: !Ref UsersRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: POST
            Path: /organizations/
            RestApiId: !Ref BillingApi                         
  
  GetOrganization:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: organizations/get_organization/
      Description: Get Organization
      FunctionName: organizations-get-organization
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /organizations/{id}
            RestApiId: !Ref BillingApi 

  ChangeOrganizationStatus:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: organizations/change_organization_status/
      Description: Get Organization
      FunctionName: organizations-change-organization-status
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: POST
            Path: /organizations/{id}/status
            RestApiId: !Ref BillingApi 

  GetOrganizationAdmin:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: organizations/get_organization_admin/
      Description: (Admin) Get Organization
      FunctionName: organizations-get-organization-admin
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /organizations/{id}/admin
            RestApiId: !Ref BillingApi 
  
  UpdateOrganization:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: organizations/update_organization/
      Description: update Organization
      FunctionName: organizations-update-organization
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: PATCH
            Path: /organizations/{id}
            RestApiId: !Ref BillingApi 
  
  DeleteOrganization:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: organizations/delete_organization/
      Description: Delete Organization
      FunctionName: organizations-delete-organization
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: DELETE
            Path: /organizations/{id}
            RestApiId: !Ref BillingApi 
  
  CheckEmailExists:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: organizations/check_email_exists/
      Description: Get Organization
      FunctionName: organizations-check-email-exists
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /organizations/email
            RestApiId: !Ref BillingApi 

  # Providers
  ListProviders:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: providers/list_providers/
      Description: List Providers
      FunctionName: providers-list-providers
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /providers
            RestApiId: !Ref BillingApi 

  # Users
  ListOrganizationUsers:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: users/list_organization_users
      Description: List Organization Users
      FunctionName: users-list-organization-users
      Role: !Ref UsersRole
      Environment:
        Variables:
          USER_POOL_ID: eu-west-1_O0r17DvOM
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /users
            RestApiId: !Ref BillingApi   
  
  ListUsersAdmin:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: users/list_users_admin
      Description: List Users (Admin)
      FunctionName: users-list-users-admin
      Role: !Ref UsersRole
      Environment:
        Variables:
          USER_POOL_ID: eu-west-1_O0r17DvOM
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /users/admin
            RestApiId: !Ref BillingApi 
  
  AddUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: users/add_user
      Description: Add User
      FunctionName: users-add-user
      Environment:
        Variables:
          USER_POOL_ID: eu-west-1_O0r17DvOM
          APP_CLIENT_ID: 574ui7l7qnhctaba7nrpuuvb4d
      Role: !Ref UsersRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: POST
            Path: /users
            RestApiId: !Ref BillingApi   
            
  GetUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: users/get_user
      Description: Get User
      FunctionName: users-get-user
      Role: !Ref UsersRole
      Environment:
        Variables:
          USER_POOL_ID: eu-west-1_O0r17DvOM
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /users/{sub}
            RestApiId: !Ref BillingApi    

  GetUserAdmin:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: users/get_user_admin
      Description: (Admin) Get User
      FunctionName: users-get-user-admin
      Role: !Ref UsersRole
      Environment:
        Variables:
          USER_POOL_ID: eu-west-1_O0r17DvOM
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /users/{sub}/admin
            RestApiId: !Ref BillingApi    
  
  # Service Connections
  ListServiceConnections:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/list_service_connections/
      Description: List Account Service Connections
      FunctionName: accounts-list-service-connections
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /accounts/{id}/services
            RestApiId: !Ref BillingApi   
    
  GetServiceConnection:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/get_service_connection/
      Description: Get a single service connection
      FunctionName: accounts-get-service-connection
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /accounts/{id}/services/{sid}
            RestApiId: !Ref BillingApi
  
  GetServiceConnectionAdmin:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/get_service_connection_admin/
      Description: (Admin) Get a single service connection
      FunctionName: accounts-get-service-connection-admin
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /accounts/{id}/services/{sid}/admin
            RestApiId: !Ref BillingApi

  ListServiceConnectionsAdmin:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/list_service_connections_admin/
      Description: (Admin) List Account Service Connections
      FunctionName: accounts-list-service-connections-admin
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /accounts/{id}/services/admin
            RestApiId: !Ref BillingApi 
  
  AddServiceConnection:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/add_service_connection/
      Description: Add Service Connection To Account
      FunctionName: accounts-add-service-connection
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: POST
            Path: /accounts/{id}/services
            RestApiId: !Ref BillingApi  
  
  DeleteServiceConnection:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/delete_service_connection/
      Description: Delete Service Connection To Account
      FunctionName: accounts-delete-service-connection
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: DELETE
            Path: /accounts/{id}/services/{sid}
            RestApiId: !Ref BillingApi  
  
  UpdateServiceConnection:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: accounts/update_service_connection/
      Description: Update Service Connection To Account
      FunctionName: accounts-update-service-connection
      Role: !Ref MainEngineRole
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: PATCH
            Path: /accounts/{id}/services/{sid}
            RestApiId: !Ref BillingApi
  
  # Documents
  CreateInvoice:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: documents/create_invoice/
      Description: Create An Invoice
      FunctionName: documents-create-invoice
      Role: !Ref MainEngineRole
      Environment:
        Variables:
          MORNING_SECRET_ARN: arn:aws:secretsmanager:eu-west-1:754084371841:secret:morning-credentials-RFREGX
      Layers:
        - 'arn:aws:lambda:eu-west-1:754084371841:layer:requests-layer:1'
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: POST
            Path: /documents/invoices
            RestApiId: !Ref BillingApi
  
  FindInvoices:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: documents/find_invoices/
      Description: Search invoices
      FunctionName: documents-find-invoices
      Role: arn:aws:iam::754084371841:role/main-engine-output-cntr
      Events:
        ApiCall:
          Type: Api
          Properties:
            Method: GET
            Path: /documents/invoices/find
            RestApiId: !Ref BillingApi

 
